name: more_elementary
description: This is architecture library with the main goal to split code between different responsibility layers, make code clear, simple, readable and easy testable.
version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  collection:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.0
  mjk_lint_rules: ^2.0.0

flutter:
  uses-material-design: true